Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine319"


  config.ssh.insert_key = false

  config.vm.define "abouassiS" do |s|
    s.vm.hostname = "abouassiS"
    s.vm.synced_folder "./confs", "/vagrant/confs", create: true
    s.vm.synced_folder "./scripts", "/vagrant/scripts", create: true
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    s.vm.provision "shell", path: "scripts/setup-master.sh"
  end
end
