Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine319"


  config.ssh.insert_key = false

  config.vm.define "abouassiS" do |s|
    s.vm.hostname = "abouassiS"
    s.vm.synced_folder "./tokens", "/vagrant/tokens", create: true
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    s.vm.provision "shell", path: "scripts/setup-master.sh"
  end

  config.vm.define "abouassiSW" do |sw|
    sw.vm.hostname = "abouassiSW"
    sw.vm.synced_folder "./tokens", "/vagrant/tokens", create: true
    sw.vm.network "private_network", ip: "192.168.56.111"
    sw.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
    sw.vm.provision "shell", path: "scripts/setup-worker.sh",args: ["192.168.56.110"]
  end
end